brew 'awscli'
brew 'git'
brew 'jq'
brew 'tmux'
brew 'tree'

cask_args appdir: '/Applications'
tap 'homebrew/cask'

cask 'docker'
cask 'google-chrome'
cask 'visual-studio-code'
cask 'karabiner-elements'
cask 'rectangle'