name: Config CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]

jobs:
  checkout:
    runs-on: macos-latest
    steps:
      - name: Recursively clone repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run setup script
        run: ./setup.sh
